name: Deploy

on:
  push:
    branches:
      - master

jobs:

  back_up_Clean:
    name: Backup and Clean
    runs-on: self-hosted
        
    steps:
      - name: check if last build is empty
        run: rm -rf HOME/lastbuild/* & mv ./* HOME/lastbuild/*
    
  
  build_server:
    name: BuildServer
    needs: back_up_Clean
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
    defaults:
      run:
        working-directory: backend/
    
    steps:
      - name: Checkout server files
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend/

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
            # cache: 'yarn'
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies & upgrade
        run:  yarn install && yarn upgrade

          #      - name: Build project
          # run:  yarn prod 
      
      - name: move to Home
        #run: run: rm -rf HOME/lastbuild/* & mv HOME./* lastbuild/* 
        run: mv $(pwd) HOME/build/server

  build_client:
    name: BuildClient
    needs: back_up_Clean
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
    defaults:
      run:
        working-directory: frontend/
    
    steps:
      - name: Checkout client files
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend/

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
            # cache: 'yarn'
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies & upgrade
        run:  yarn install && yarn upgrade

      - name: Build project
        run:  yarn run build
      
      - name: move to Home
        run: mv -f $(pwd)/lastBuild && mv (pwd)/dist HOME/build/
          ## - name: move to Home
          ##run: mv -r ../frontend/ ~/build/client
        
  
  deploy:
    name: Deploy
    needs: [build_client,build_server]
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: $HOME/build

    steps:
      - name: make backup folder
        run:  mkdir /home/ubuntu/backups/$(date '+%Y_%m_%d_%H_%M')

      - name: backup old site
        run:  cp -r /var/www/html/* /home/ubuntu/backups/$(date '+%Y_%m_%d_%H_%M') 
      
      - name: Clear contents of /var/www/html
        run:  rm -rf /var/www/html/*
      
      - name: deploy new site
        run:  cp -r dist/ /var/www/html/

