name: Deploy

on:
  push:
    branches:
      - master

jobs:
  
  build_server:
    name: BuildServer
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
          #defaults:
          #run:
          #working-directory: backend/
    
    steps:
      - name: Checkout server files
        uses: Bhacaz/checkout-files@v2
        with:
          files: backend/
            #uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
            # cache: 'yarn'
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies & upgrade
        run:  yarn install && yarn upgrade

      - name: Build project
        run:  yarn start
  
  build_client:
    name: BuildClient
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
    defaults:
      run:
        working-directory: frontend/
    
    steps:
      - name: Checkout client files
        uses: Bhacaz/checkout-files@v2
        with:
          files: frontend/
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
            # cache: 'yarn'
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies & upgrade
        run:  yarn install && yarn upgrade

      - name: Build project
        run:  yarn run build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: make backup folder
        run:  mkdir /home/ubuntu/backups/$(date '+%Y_%m_%d_%H_%M')

      - name: backup old site
        run:  cp -r /var/www/html/* /home/ubuntu/backups/$(date '+%Y_%m_%d_%H_%M') 
      
      - name: Clear contents of /var/www/html
        run:  rm -rf /var/www/html/*
      
      - name: deploy new site
        run:  cp -r ./frontend/dist/ /var/www/html/

