name: Deploy

on:
  push:
    branches:
      - master

jobs:

  back_up_Clean:
    name: Backup and Clean
    runs-on: self-hosted
    env:
      #date_fd: !timestamp '2023-02-07T08:30:00Z'
        #$(date '+%Y_%m_%d_%H_%M') 
      home_dir: /home/ubuntu
      build_fd: /home/ubuntu/build
        
    steps:
      - name: set date
        run: echo "date_fd=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Disable Syncthing
        run: ( ! (systemctl is-active syncthing && sudo systemctl stop syncthing && systemctl is-active syncthing)); 
      - name: Disable nodeserver
        run:  ( ! (systemctl is-active nodeserver && sudo systemctl stop syncthing && systemctl is-active syncthing))
      - name: Backup build folder  
        run: mkdir --parents $home_dir/backups/$date_fd 
      - run: mv  $build_fd/*  $home_dir/backups/$date_fd/ ;
      - name: Copy md from old site
        run:  cp $home_dir/backups/$Date_fd/frontend/dist/*.md $build_fd/dist/;
      
      - name: Clean up node_modules;
        run: rm -rf $home_dir/backups/$date_fd/frontend/node_modules && rm -rf $home_dir/backups/$date_fd/backend/node_modules
  
  build_server:
    name: BuildServer
    needs: back_up_Clean
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
    defaults:
      run:
        working-directory: backend/
    
    steps:
      - name: Checkout server files
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend/

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies 
        run:  yarn install
      
      - name: move to home build folder
        run: mv -f ../* /home/ubuntu/build/

  build_client:
    name: BuildClient
    needs: back_up_Clean
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
     
    defaults:
      run:
        working-directory: frontend/
    
    steps:
      - name: Checkout client files
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend/

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
            # cache: 'yarn'
      
      - name: clear old modules & lock
        run:  rm -rf node_modules *lock*

      - name: Install dependencies & upgrade
        run:  yarn install
          # && yarn upgrade

      - name: Build project
        run:  yarn run build
      
      - name: move to build
        run: mv -f ../* /home/ubuntu/build/
        
  restart_servers:
    name: Restart Servers
    needs: [build_client, build_server]
    runs-on: self-hosted
    steps:
      - name: Restart Syncthing
        run: if ( ! systemctl is-active syncthing ) ; then sudo systemctl start syncthing; fi
      - name: Restart nodeserver
        run: if ( ! systemctl is-active nodeserver ) ; then  sudo systemctl start nodeserver; fi 
          # deploy:
          #   name: Deploy
          #   needs: [build_client,build_server]
          #   runs-on: self-hosted
          #   env:
          #     home_dir: "/home/ubuntu"
          #     web_dir: "/var/www/html"

          #   steps:
      #- name: make backup folder

      # run: if [ -d $web_dir ];
      #        then mkdir --parents "$home_dir/backups/$Date_fd" && mv -f $web_dir/*  "$home_dir/backups/$Date_fd";
      #        fi
      #  env:
      #    Date_fd: "$(date '+%Y_%m_%d_%H_%M')" 
      
            #- name: deploy new site
        #        run:  cp -r $home_dir/build/frontend/dist $web_dir/* 
          # - run:  cd $home_dir/build/backend && yarn start

